### ISSUE TITLE
Error when installing `ios-deploy`on macOS

### ISSUE THREAD

**Issue by andymurakami** [alrra/dotfiles#39]
When executing the command ionic build ios, the console got me to install ionic-sim and ionic-deploy, while installing ionic delploy gave the following error:

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   '--unsafe-perm',
1 verbose cli   'ios-deploy' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData ios-deploy
8 silly fetchNamedPackageData ios-deploy
9 silly mapToRegistry name ios-deploy
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'ios-deploy',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'ios-deploy',
12 silly mapToRegistry   name: 'ios-deploy',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/ios-deploy
14 verbose request uri https://registry.npmjs.org/ios-deploy
15 verbose request no auth needed
16 info attempt registry request try #1 at 13:36:31
17 verbose request id 59c449b54fc1ef34
18 verbose etag W/"58042da1-9e49"
19 verbose lastModified Mon, 17 Oct 2016 01:47:13 GMT
20 http request GET https://registry.npmjs.org/ios-deploy
21 http 304 https://registry.npmjs.org/ios-deploy
22 verbose headers { date: 'Fri, 23 Dec 2016 15:36:31 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"58042da1-9e49"',
22 verbose headers   age: '0',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-gru7125-GRU',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1482507391.635999,VS0,VE181',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Fri, 23 Dec 2016 15:36:31 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"58042da1-9e49"',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-gru7125-GRU',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1482507391.635999,VS0,VE181',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/ios-deploy from cache
25 verbose get saving ios-deploy to /Users/rubiamanfroi/.npm/registry.npmjs.org/ios-deploy/.cache.json
26 verbose correctMkdir /Users/rubiamanfroi/.npm correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly resolveWithNewModule ios-deploy@1.9.0 checking installable status
40 silly cache add args [ 'ios-deploy', null ]
41 verbose cache add spec ios-deploy
42 silly cache add parsed spec Result {
42 silly cache add   raw: 'ios-deploy',
42 silly cache add   scope: null,
42 silly cache add   escapedName: 'ios-deploy',
42 silly cache add   name: 'ios-deploy',
42 silly cache add   rawSpec: '',
42 silly cache add   spec: 'latest',
42 silly cache add   type: 'tag' }
43 silly addNamed ios-deploy@latest
44 verbose addNamed "latest" is being treated as a dist-tag for ios-deploy
45 info addNameTag [ 'ios-deploy', 'latest' ]
46 silly mapToRegistry name ios-deploy
47 silly mapToRegistry using default registry
48 silly mapToRegistry registry https://registry.npmjs.org/
49 silly mapToRegistry data Result {
49 silly mapToRegistry   raw: 'ios-deploy',
49 silly mapToRegistry   scope: null,
49 silly mapToRegistry   escapedName: 'ios-deploy',
49 silly mapToRegistry   name: 'ios-deploy',
49 silly mapToRegistry   rawSpec: '',
49 silly mapToRegistry   spec: 'latest',
49 silly mapToRegistry   type: 'tag' }
50 silly mapToRegistry uri https://registry.npmjs.org/ios-deploy
51 verbose addNameTag registry:https://registry.npmjs.org/ios-deploy not in flight; fetching
52 verbose get https://registry.npmjs.org/ios-deploy not expired, no request
53 silly addNameTag next cb for ios-deploy with tag latest
54 silly addNamed ios-deploy@1.9.0
55 verbose addNamed "1.9.0" is a plain semver version for ios-deploy
56 silly cache afterAdd ios-deploy@1.9.0
57 verbose afterAdd /Users/rubiamanfroi/.npm/ios-deploy/1.9.0/package/package.json not in flight; writing
58 verbose correctMkdir /Users/rubiamanfroi/.npm correctMkdir not in flight; initializing
59 verbose afterAdd /Users/rubiamanfroi/.npm/ios-deploy/1.9.0/package/package.json written
60 silly loadAllDepsIntoIdealTree Finishing
61 silly loadIdealTree Finishing
62 silly currentTree lib
63 silly idealTree lib
63 silly idealTree └── ios-deploy@1.9.0
64 silly generateActionsToTake Starting
65 silly install generateActionsToTake
66 silly generateActionsToTake Finishing
67 silly diffTrees action count 1
68 silly diffTrees add ios-deploy@1.9.0
69 silly decomposeActions action count 8
70 silly decomposeActions fetch ios-deploy@1.9.0
71 silly decomposeActions extract ios-deploy@1.9.0
72 silly decomposeActions test ios-deploy@1.9.0
73 silly decomposeActions preinstall ios-deploy@1.9.0
74 silly decomposeActions build ios-deploy@1.9.0
75 silly decomposeActions install ios-deploy@1.9.0
76 silly decomposeActions postinstall ios-deploy@1.9.0
77 silly decomposeActions finalize ios-deploy@1.9.0
78 silly runTopLevelLifecycles Starting
79 silly executeActions Starting
80 silly install executeActions
81 silly doSerial global-install 0
82 silly doParallel fetch 1
83 verbose correctMkdir /Users/rubiamanfroi/.npm/_locks correctMkdir not in flight; initializing
84 verbose lock using /Users/rubiamanfroi/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
85 silly doParallel extract 1
86 silly extract ios-deploy@1.9.0
87 verbose unbuild lib/node_modules/.staging/ios-deploy-298c9491
88 silly gentlyRm /usr/local/lib/node_modules/.staging/ios-deploy-298c9491 is being purged from base /usr/local
89 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/.staging/ios-deploy-298c9491
90 verbose tar unpack /Users/rubiamanfroi/.npm/ios-deploy/1.9.0/package.tgz
91 verbose tar unpacking to /usr/local/lib/node_modules/.staging/ios-deploy-298c9491
92 silly gentlyRm /usr/local/lib/node_modules/.staging/ios-deploy-298c9491 is being purged
93 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/.staging/ios-deploy-298c9491
94 silly gunzTarPerm modes [ '755', '644' ]
95 silly gunzTarPerm extractEntry package.json
96 silly gunzTarPerm extractEntry .npmignore
97 silly gunzTarPerm extractEntry README.md
98 silly gunzTarPerm extractEntry LICENSE
99 silly gunzTarPerm extractEntry demo/.npmignore
100 silly gunzTarPerm extractEntry demo/Entitlements.plist
101 silly gunzTarPerm extractEntry demo/Info.plist
102 silly gunzTarPerm extractEntry demo/Makefile
103 silly gunzTarPerm extractEntry demo/ResourceRules.plist
104 silly gunzTarPerm extractEntry demo/demo.c
105 silly gunzTarPerm extractEntry ios-deploy.xcodeproj/project.pbxproj
106 silly gunzTarPerm extractEntry ios-deploy.xcodeproj/project.xcworkspace/contents.xcworkspacedata
107 silly gunzTarPerm extractEntry ios-deploy.xcodeproj/project.xcworkspace/xcuserdata/shazron.xcuserdatad/UserInterfaceState.xcuserstate
108 silly gunzTarPerm extractEntry ios-deploy.xcodeproj/xcshareddata/xcschemes/ios-deploy-tests.xcscheme
109 silly gunzTarPerm extractEntry ios-deploy.xcodeproj/xcuserdata/shazron.xcuserdatad/xcschemes/ios-deploy-lib.xcscheme
110 silly gunzTarPerm extractEntry ios-deploy.xcodeproj/xcuserdata/shazron.xcuserdatad/xcschemes/ios-deploy.xcscheme
111 silly gunzTarPerm extractEntry ios-deploy.xcodeproj/xcuserdata/shazron.xcuserdatad/xcschemes/xcschememanagement.plist
112 silly gunzTarPerm extractEntry CONTRIBUTING.md
113 silly gunzTarPerm extractEntry src/ios-deploy/MobileDevice.h
114 silly gunzTarPerm extractEntry src/ios-deploy/errors.h
115 silly gunzTarPerm extractEntry src/ios-deploy/ios-deploy.m
116 silly gunzTarPerm extractEntry src/ios-deploy/version.h
117 silly gunzTarPerm extractEntry src/ios-deploy-lib/libios_deploy.h
118 silly gunzTarPerm extractEntry src/ios-deploy-lib/libios_deploy.m
119 silly gunzTarPerm extractEntry src/ios-deploy-tests/Info.plist
120 silly gunzTarPerm extractEntry src/ios-deploy-tests/ios_deploy_tests.m
121 silly gunzTarPerm extractEntry src/scripts/check_reqs.js
122 silly gunzTarPerm extractEntry src/scripts/lldb.py
123 silly gentlyRm /usr/local/lib/node_modules/.staging/ios-deploy-298c9491/node_modules is being purged
124 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/.staging/ios-deploy-298c9491/node_modules
125 silly doParallel preinstall 1
126 silly preinstall ios-deploy@1.9.0 /usr/local/lib/node_modules/.staging/ios-deploy-298c9491
127 info lifecycle ios-deploy@1.9.0~preinstall: ios-deploy@1.9.0
128 verbose lifecycle ios-deploy@1.9.0~preinstall: unsafe-perm in lifecycle true
129 verbose lifecycle ios-deploy@1.9.0~preinstall: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/lib/node_modules/.staging/ios-deploy-298c9491/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
130 verbose lifecycle ios-deploy@1.9.0~preinstall: CWD: /usr/local/lib/node_modules/.staging/ios-deploy-298c9491
131 silly lifecycle ios-deploy@1.9.0~preinstall: Args: [ '-c', './src/scripts/check_reqs.js && xcodebuild' ]
132 silly lifecycle ios-deploy@1.9.0~preinstall: Returned: code: 1  signal: null
133 info lifecycle ios-deploy@1.9.0~preinstall: Failed to exec preinstall script
134 verbose unlock done using /Users/rubiamanfroi/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
135 silly rollbackFailedOptional Starting
136 silly rollbackFailedOptional Finishing
137 silly runTopLevelLifecycles Finishing
138 silly install printInstalled
139 verbose stack Error: ios-deploy@1.9.0 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
139 verbose stack Exit status 1
139 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
139 verbose stack     at emitTwo (events.js:106:13)
139 verbose stack     at EventEmitter.emit (events.js:191:7)
139 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
139 verbose stack     at emitTwo (events.js:106:13)
139 verbose stack     at ChildProcess.emit (events.js:191:7)
139 verbose stack     at maybeClose (internal/child_process.js:877:16)
139 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
140 verbose pkgid ios-deploy@1.9.0
141 verbose cwd /Users/rubiamanfroi/ofertas
142 error Darwin 16.0.0
143 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "--unsafe-perm" "ios-deploy"
144 error node v6.9.2
145 error npm  v3.10.9
146 error code ELIFECYCLE
147 error ios-deploy@1.9.0 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
147 error Exit status 1
148 error Failed at the ios-deploy@1.9.0 preinstall script './src/scripts/check_reqs.js && xcodebuild'.
148 error Make sure you have the latest version of node.js and npm installed.
148 error If you do, this is most likely a problem with the ios-deploy package,
148 error not with npm itself.
148 error Tell the author that this fails on your system:
148 error     ./src/scripts/check_reqs.js && xcodebuild
148 error You can get information on how to open an issue for this project with:
148 error     npm bugs ios-deploy
148 error Or if that isn't available, you can get their info via:
148 error     npm owner ls ios-deploy
148 error There is likely additional logging output above.
149 verbose exit [ 1, true ]
```

Thanks in advance

**Comment by alrra** [comment]
@andymurakami You should follow the instructions from the logs:

> 148 error Make sure you have the latest version of node.js and npm installed.
148 error If you do, this is most likely a problem with the ios-deploy package,
148 error not with npm itself.
148 error Tell the author that this fails on your system:
148 error     ./src/scripts/check_reqs.js && xcodebuild
148 error You can get information on how to open an issue for this project with:
148 error     npm bugs ios-deploy
148 error Or if that isn't available, you can get their info via:
148 error     npm owner ls ios-deploy

---

Closing as this repository doesn't have anything to do with `ionic`.
